### ISSUE TITLE
Error at starting when addon is downloaded from Anki

### ISSUE THREAD

**Issue by corderop** [corderop/anki-github-markdown#1]
A user left this comment:

> Not sure if my OS is Linux Ubuntu so this kind of problem occurs...
> 
> ```
> Error
> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
> 
> When loading '⁨GitHub Markdown⁩':
> ⁨Traceback (most recent call last):
> File "aqt.addons", line 247, in loadAddons
> File "/home/my_admin/.local/share/Anki2/addons21/871222788/__init__.py", line 1, in <module>
> from .anki.editor_button import EditorButton
> ModuleNotFoundError: No module named '871222788.anki'
```

In a quick check, this is only happening when installing the addon with the anki code, it's not happening when you load the addon during development.

**Comment by corderop** [comment]
Solved reupdating the zip file with the `.ankiaddon` extensions instead of `.zip`
